# Generated by Django 3.1 on 2020-08-20 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('beauty', 'Beauty'), ('trends', 'Trends'), ('travel', 'Travel'), ('fashion', 'Fashion'), ('culture', 'Culture'), ('food', 'Food'), ('entrepreneur', 'Entrepreneur'), ('fashion-pictorial', 'Fashion Pictorial'), ('health', 'Health'), ('men', 'Mens Corner'), ('lifestyle', 'Lifestyle'), ('general', 'General')], default='general', max_length=20, verbose_name='Category Name')),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_tag', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.category')),
            ],
        ),
    ]
